### ISSUE TITLE
How to get the response from Close.io

### ISSUE THREAD

**Issue by lee-40square** [wehriam/Close.io#1]
Close.io returns a response. How to I read that?

**Comment by wehriam** [comment]
Responses are passed via promises - https://github.com/kriszyp/node-promise

`closeio.lead.read(SOME_LEAD_ID).then(function(success_response) {}, function(error_response) {});`

**Comment by wehriam** [comment]
Please contact Elastic at https://github.com/elasticsales/closeio-node for future issues.
